"""check sync

Revision ID: 23b599ed4f1d
Revises: f1a2b3c4d5e6
Create Date: 2026-06-11 14:19:37.170693

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '23b599ed4f1d'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_active')
    op.drop_column('companies', 'name_en')
    op.drop_column('companies', 'sort_order')
    op.drop_constraint('fk_positions_company', 'positions', type_='foreignkey')
    op.drop_column('positions', 'company_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_positions_company', 'positions', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('companies', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('name_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
